FE=float(input('Foundation English :'))
GB=float(input('General Business :'))
IC=float(input('Introduction to Computer Systems :'))
CP=float(input('Computer Programming :'))
print("--- Your Score ---")
print("Foundation English :",FE," score")
print("General Business :",GB," score")
print("Introduction to Computer Systems :",IC," score")
print("Computer Programming :",CP," score")
